version: "3"
services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: simple_bank
  redis:
    image: redis:7.2.5-alpine
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_SOURCE=postgresql://root:admin@db:5432/simple_bank?sslmode=disable
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    entrypoint: ["/app/start.sh"]
