name: Infra update

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/infra.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/infra.yaml"
  workflow_dispatch:

env:
  TF_VERSION: 1.9.1

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TF_VERSION}}

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Format
        working-directory: infra
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        working-directory: infra
        run: TF_VAR_DB_PASSWORD=${{secrets.DB_PASSWORD}} terraform plan --out plan.output

      - uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/plan.output

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{env.TF_VERSION}}

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: infra/

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply --auto-approve plan.output
